// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function SaveBase64File(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
