// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['services']['preferencesService']['CheckForUpdate']();
}

export function GetAppVersion() {
  return window['go']['services']['preferencesService']['GetAppVersion']();
}

export function GetBuildInDecoder() {
  return window['go']['services']['preferencesService']['GetBuildInDecoder']();
}

export function GetFontList() {
  return window['go']['services']['preferencesService']['GetFontList']();
}

export function GetLanguage() {
  return window['go']['services']['preferencesService']['GetLanguage']();
}

export function GetPreferences() {
  return window['go']['services']['preferencesService']['GetPreferences']();
}

export function GetScanSize() {
  return window['go']['services']['preferencesService']['GetScanSize']();
}

export function GetWindowPosition(arg1) {
  return window['go']['services']['preferencesService']['GetWindowPosition'](arg1);
}

export function GetWindowSize() {
  return window['go']['services']['preferencesService']['GetWindowSize']();
}

export function RestorePreferences() {
  return window['go']['services']['preferencesService']['RestorePreferences']();
}

export function SaveWindowPosition(arg1, arg2) {
  return window['go']['services']['preferencesService']['SaveWindowPosition'](arg1, arg2);
}

export function SaveWindowSize(arg1, arg2, arg3) {
  return window['go']['services']['preferencesService']['SaveWindowSize'](arg1, arg2, arg3);
}

export function SetAppVersion(arg1) {
  return window['go']['services']['preferencesService']['SetAppVersion'](arg1);
}

export function SetPreferences(arg1) {
  return window['go']['services']['preferencesService']['SetPreferences'](arg1);
}

export function UpdateEnv() {
  return window['go']['services']['preferencesService']['UpdateEnv']();
}

export function UpdatePreferences(arg1) {
  return window['go']['services']['preferencesService']['UpdatePreferences'](arg1);
}
