server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Direct access to sitemap.xml and robots.txt
    location ~ ^/(sitemap\.xml|robots\.txt)$ {
        try_files $uri =404;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}