// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function CheckForUpdate():Promise<types.JSResp>;

export function GetAppVersion():Promise<types.JSResp>;

export function GetBuildInDecoder():Promise<types.JSResp>;

export function GetFontList():Promise<types.JSResp>;

export function GetLanguage():Promise<string>;

export function GetPreferences():Promise<types.JSResp>;

export function GetScanSize():Promise<number>;

export function GetWindowPosition(arg1:context.Context):Promise<number|number>;

export function GetWindowSize():Promise<number>;

export function RestorePreferences():Promise<types.JSResp>;

export function SaveWindowPosition(arg1:number,arg2:number):Promise<void>;

export function SaveWindowSize(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetAppVersion(arg1:string):Promise<void>;

export function SetPreferences(arg1:types.Preferences):Promise<types.JSResp>;

export function UpdateEnv():Promise<void>;

export function UpdatePreferences(arg1:{[key: string]: any}):Promise<types.JSResp>;
